---
version: '2.2'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    volumes:
      - /usr/share/elasticsearch/data
    ports:
      - "9200"
      - "9300"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    scale: 3
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
